name = "malevitamin-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "malevitamin.co.za/*", zone_name = "malevitamin.co.za" },
  { pattern = "www.malevitamin.co.za/*", zone_name = "malevitamin.co.za" }
]
